FROM alpine:latest
## WORK IN PROGRESS - minimalizing build/size
RUN apk add update \ 
    && apk upgrade 
RUN apk add curl 
RUN apk add python2.7 

RUN apk add powershell
RUN apk add sudo
RUN apk add git
RUN ln -s /usr/bin/python2.7 /usr/bin/python

RUN apk add unzip

RUN apt-get install -y build-essential libssl-dev libffi-dev libpython2-dev python-dev 

RUN pwsh -Command "&{Install-Module -Name Az -AllowClobber -Scope AllUsers -Force}"
# AzureCLI - alpine
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# PIP WITH Python2.7 is deprecated. Also - msgen only supporting Python2.7 .
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python get-pip.py

# Microsoft Genomics
RUN pip install --upgrade --no-deps msgen
RUN pip install msgen

# Bicep on cli
RUN az bicep install

RUN apt-get install zip unzip
# Bicep on Powershell
# Fetch the latest Bicep CLI binary
RUN curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
# Mark it as executable
RUN chmod +x ./bicep
# Add bicep to your PATH (requires admin)
RUN mv ./bicep /usr/local/bin/bicep
# Verify you can now access the 'bicep' command

# Azure User context
RUN useradd -m azureuser
USER azureuser
# Can always use the container/run interactive witH docker run -it haraldf/azuretools:latest
RUN mkdir $HOME/git

RUN unzip $HOME/arm-ttk.zip -d $HOME/.local/share/powershell/Modules/
## https://aka.ms/arm-ttk-latest
CMD [ "pwsh" ]