name: Build and push latest Azure Tools

on:
  push:
    branches: [ main ]
    paths: 
      - Containers/AzureTools/Dockerfile
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Containers/AzureTools/Dockerfile --tag haraldf/azuretools:$(date +%s) --tag haraldf/azuretools:latest

    - name: Login to Docker Hub
      if:  ${{ github.ref == 'ref/head/main'}} 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the image to docker hub
      if:  ${{ github.ref == 'ref/head/main'}} 
      run: |
        docker image push haraldf/azuretools:latest
      
