name: Build and push latest Azure Tools docker image

on:
  push:
    branches: [ main ]
    paths: 
      - Containers/AzureTools/Dockerfile
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 23 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache . --file Containers/AzureTools/Dockerfile --tag haraldf/azuretools:$(date +%d%m%Y) --tag haraldf/azuretools:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the images to docker hub
      run: |
        docker image push haraldf/azuretools:latest         
        if [[ $BRANCH == 'main' && $GITHUB_EVENT_NAME == 'push' ]]; then
          docker image push haraldf/azuretools:$(date +%d%m%Y)    
        else
            echo 'Skipping date tags - recurring build - only pushing latest'
        fi              
